In [26]:
from load_image import ft_load
import numpy as np
from PIL import Image
from pimp_image import ft_invert, ft_red

array: np.ndarray = ft_load("../img/landscape.jpg")

In [ ]:
Image.fromarray(ft_invert(array)).show()

In [46]:
# print(ft_red(array))
array: np.ndarray = ft_load("../img/landscape.jpg")
print(f"array = {array}")
array = array[:, :, [0]]
narray = np.reshape(array, (array.shape[0], array.shape[1], 3))
print(f"narray = {narray}")
Image.fromarray(narray).show()
# Image.fromarray(ft_red(array)).show()

array = [[[19 42 83]
  [23 42 84]
  [28 43 84]
  ...
  [69 42 51]
  [68 41 46]
  [68 41 46]]

 [[20 43 84]
  [24 43 85]
  [28 43 84]
  ...
  [71 44 53]
  [71 42 47]
  [71 42 47]]

 [[22 44 85]
  [25 44 84]
  [30 45 86]
  ...
  [74 44 54]
  [72 43 48]
  [72 43 48]]

 ...

 [[ 1  0  5]
  [ 1  0  5]
  [ 1  0  5]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 1  0  5]
  [ 1  0  5]
  [ 1  0  5]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  4]
  [ 0  0  4]
  [ 0  0  4]
  ...
  [ 0  0  0]
  [ 1  1  1]
  [ 1  1  1]]]


ValueError: cannot reshape array of size 115650 into shape (257,450,3)